spring:
  application:
    name: spring-cloud-eureka-feign-client

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    enabled: true
  instance:
    prefer-ip-address: true

hystrix:
  command:
    greeting:
      circuitBreaker:
        requestVolumeThreshold: 15
        sleepWindowInMilliseconds: 8000
        errorThresholdPercentage: 50

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream